In [ ]:
from sklearn.model_selection import GridSearchCV

params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

In [ ]:
gs= GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
# n_jobs=-1은 사용 가능한 CPU core를 갖고 진행하도록 함

In [ ]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [ ]:
dt=gs.best_estimator_
print(dt.score(train_input, train_target))

0.9615162593804117


In [ ]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [ ]:
print(gs.cv_results_['mean_test_score'])
# 모든 하이퍼파라미터 조합에 대한 교차 검증 결과를 담고있는 딕셔너리
# params에 5개의 하이퍼파라미터 조합이있고 각 값은 해당 조합에 대한 5-fold 교차검증의 평균 테스트 점수

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [ ]:
best_index = np.argmax(gs.cv_results_['mean_test_score'])
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [ ]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),#9개
          'max_depth': range(5,20,1),#15개
          'min_samples_split': range(2,100,10)#10개
          }


In [ ]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)
#9*15*10*5개 폴드 =6750개의 모델을 테스트함

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [ ]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731


In [ ]:
from scipy.stats import uniform, randint

In [ ]:
rgen= randint(0,10)
rgen.rvs(10)

array([7, 9, 4, 7, 1, 3, 4, 6, 4, 6])

In [ ]:
np.unique(rgen.rvs(1000), return_counts=True)
# 0에서 9까지의 값이 생성, 각 값의 등장 횟수 출력.

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([107,  96,  92, 107,  92,  93, 116, 109,  91,  97]))

In [ ]:
ugen = uniform(0, 1)
ugen.rvs(10)
# 0이상 1 미만의 실수 값으로 균일하게 분포됨

array([0.78103363, 0.02951369, 0.28033577, 0.64315163, 0.04338918,
       0.80003857, 0.68699247, 0.95946171, 0.01577354, 0.70570357])

In [ ]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001),
          'max_depth': range(20, 50),
          'min_samples_split': randint(2,25),
          'min_smaples_leaf': randint(1,25)}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

gs= RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params,
                       n_iter=100, n_jobs=-1, random_state=42) # n_iter=100은 위의 params 샘플링을 100번 수행

gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': range(5, 20),
                                        'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                                        'min_samples_split': range(2, 100, 10)},
                   random_state=42)

In [ ]:
print(gs.best_params_)

{'min_samples_split': 12, 'min_impurity_decrease': np.float64(0.0005), 'max_depth': 11}


In [ ]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8681935292811135


In [ ]:
dt=gs.best_estimator_

print(dt.score(test_input, test_target))

0.8615384615384616
